server:
  extends:
    file: common.yml
    service: server
  image: quay.io/jrgm_docker/teamcity-server
  restart: always

agent:
  extends:
    file: common.yml
    service: agent
  image: quay.io/jrgm_docker/teamcity-agent-centos
  links:
    - server
  restart: always
